### ISSUE TITLE
client = Client.open("https://stac.staging.digitalearthpacific.org") # does not work

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/dep-geomad#5]
1. `client = Client.open("https://stac.staging.digitalearthpacific.org") # does not work` results in the following error: 

AttributeError: type object 'Client' has no attribute 'open'

![image](https://github.com/digitalearthpacific/dep-geomad/assets/67347387/20da4f77-a755-4fb0-aba7-bede73ed685d)

**Comment by alexgleith** [comment]
I just logged into the analytics hub, and ran the first two cells of the notebook and it worked fine.

Pic below.

What is the environment you're working in?

What is the output of `pip freeze | grep pystac`

<img width="1183" alt="image" src="https://github.com/digitalearthpacific/dep-geomad/assets/3445853/ebd80924-5819-4f03-94af-3fd305620f18">

**Comment by nicholasmetherall** [comment]
`pip freeze | grep pystac`

pystac @ file:///home/conda/feedstock_root/build_artifacts/pystac_1682516922068/work
pystac-client @ file:///home/conda/feedstock_root/build_artifacts/pystac-client_1686676387449/work
Note: you may need to restart the kernel to use updated packages.

![image](https://github.com/digitalearthpacific/dep-geomad/assets/67347387/dcabe28b-e147-41ec-ab24-3629a0c89eb1)

**Comment by alexgleith** [comment]
Ok, so if you paste this into a new notebook at run it, does it work?

```
from pystac_client import Client

client = Client.open("https://stac.staging.digitalearthpacific.org")
```

What you might be doing is importing the Dask client as well as the pystac client.

You can change the name of the imported library like this: `from pystac_client import Client as PystacClient` and then open the catalog with that `PystacClient.open()`.

**Comment by nicholasmetherall** [comment]
Thanks for the workaround.
